version: 3

methods:
  youtube:
    title: YouTube
    enabled: true

  ia_wayback:
    title: Wayback Machine
    enabled: true

  ia_details:
    title: Archive.org Details
    enabled: true

  ia_cdx:
    title: Archive.org CDX
    enabled: true

  ghostarchive:
    title: GhostArchive
    enabled: true

  hackint_ya:
    title: "#youtubearchive"
    enabled: false
    username:
    password:

  distributed_youtube_archive:
    title: Distributed YouTube Archive
    enabled: true

  hobune_stream:
    title: Hobune.stream
    enabled: true

  filmot:
    title: Filmot
    enabled: false
    api_key:

  playboard_co:
    title: Playboard.co
    enabled: true

  removededm:
    title: Removed.edm
    enabled: true

  odysee:
    title: Odysee
    enabled: true

  altcensored:
    title: altCensored
    enabled: true

  preservetube:
    title: PreserveTube
    enabled: true

# Global User-Agent
# user_agent: "MyCustomUserAgent/1.0"
